name: lightInventory
author: lightPlugins
version: 1.0.0
main: io.lightplugins.inventory.LightMaster
api-version: 1.18
depend: [Vault]
softdepend: [HeadDatabase]
loadbefore: []
libraries: []
#  - org.mariadb.jdbc:mariadb-java-client:2.7.4
#  - com.zaxxer:HikariCP:5.1.0
commands:
  li:
    description: The root command for lightInventory overall
    aliases: [lightinventory, lightinv]